package:
  name: qfield
  version: 1.4.1

source:
  fn: windows-azure-pipeline.tar.gz
  url: https://github.com/opengisch/QField/archive/windows-azure-pipeline.tar.gz
  md5: 942162488570a643e9da7c986b3bcbe3

build:
  features:
    - vc9     [win and py27]
    - vc10    [win and py34]
    - vc14    [win and py35]

build:
  number: 1

requirements:
  build:
    - qgis
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  run:
    - qgis

about:
  home: http://qfield.og
  license: GPL-2.0
