# version numbering is explained at https://stackoverflow.com/questions/42730478/version-numbers-for-visual-studio-2017-boost-and-cmake
#     This version number follows the "platform toolset"
{% set vcver="14.1" %}
{% set vsyear="2019" %}
# VS2017 is fundamentally compatible with VS2015.  We name our package vs2015_runtime so that it can't be
#    mixed up with the runtime from VS2015 - you do actually need VS2017 runtime for things compiled with
#    VS2017, and the runtime we have here is backwards-compatible with things compiled with VS2015.
{% set runtime_year="2015" %}


package:
  name: qfield
  version: 1.4.1

source:
  fn: windows-azure-pipeline.tar.gz
  url: https://github.com/opengisch/QField/archive/windows-azure-pipeline.tar.gz
  md5: 942162488570a643e9da7c986b3bcbe3

build:
  features:
    - vc9     [win and py27]
    - vc10    [win and py34]
    - vc14    [win and py35]

build:
  number: 1

requirements:
  build:
    - qgis
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  run:
    - qgis

about:
  home: http://qfield.og
  license: GPL-2.0
