package:
  name: libtiff
  version: 4.1.0

source:
  fn: tiff-4.1.0.tar.gz
  url: https://download.osgeo.org/libtiff/tiff-4.1.0.tar.gz
  md5: 2165e7aba557463acc0664e71a3ed424

build:
  features:
    - vc9     [win and py27]
    - vc10    [win and py34]
    - vc14    [win and py35]

build:
  number: 1

requirements:
  build:
    - zlib
    - jpeg
    - xz   # provides liblzma
    - jbig # [not win]
  run:
    - zlib
    - jpeg
    - xz   # provides liblzma
    - jbig # [not win]

about:
  home: http://www.libtiff.org/
  license: as-is (http://www.libtiff.org/misc.html)
