on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  example-2-win:
    name: Windows Build
    runs-on: 'windows-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          miniconda-version: 'latest'
          activate-environment: foo

      - name: Install conda-build
        shell: cmd /C CALL {0}
        run: >-
          conda install conda-build

      - name: Configure x64
        if: runner.os == 'Windows'
        run: .github\workflows\vsenv.bat -arch=x64 -host_arch=x64

      - name: Build qfield
        shell: cmd /C CALL {0}
        run: >-
          conda-build -c conda-forge conda-recipes/qfield
