on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  example-2-win:
    name: Windows Build
    runs-on: 'windows-latest'
    steps:
      - uses: actions/checkout@v2

      - uses: goanpeca/setup-miniconda@v1
        with:
          miniconda-version: 'latest'
          activate-environment: foo

      - name: Install conda-build
        shell: cmd /C CALL {0}
        run: >-
          conda install conda-build

      - name: Build libtiff
        shell: cmd /C CALL {0}
        run: >-
          conda-build conda-recipes/libtiff

      - name: Build qt5
        shell: cmd /C CALL {0}
        run: >-
          conda-build conda-recipes/qt5
